version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./TaskManager.Deployment/docker/api/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  messaging:
    build:
      context: .
      dockerfile: ./TaskManager.Deployment/docker/messaging/Dockerfile
    ports:
     - "5001:5001"
    volumes:
     - .:/code
  apidb:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "YourStrong!Passw0rd"
        ACCEPT_EULA: "Y"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15682:80"
      - "5682:80"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config