version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./TaskManager.Deployment/docker/api/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  messaging:
    build:
      context: .
      dockerfile: ./TaskManager.Deployment/docker/messaging/Dockerfile
    ports:
     - "5001:5001"
    volumes:
     - .:/code