USE [master]
GO
IF(db_id(N'$(DATABASE_NAME)') IS NULL) CREATE DATABASE [$(DATABASE_NAME)];
GO
IF NOT EXISTS ((SELECT name FROM sys.server_principals WHERE name = '$(USER_NAME)'))
CREATE LOGIN [$(USER_NAME)] WITH PASSWORD=N'$(PASSWORD)' 
GO
USE [$(DATABASE_NAME)]
GO
IF NOT EXISTS ((SELECT name FROM sys.database_principals WHERE name = '$(USER_NAME)'))
CREATE USER [$(USER_NAME)] FOR LOGIN [$(USER_NAME)]
GO
ALTER ROLE [db_owner] ADD MEMBER [$(USER_NAME)]
GO
