version: '3'
services:
  api:
    build:
      context: ./docker/api
      dockerfile: ./Dockerfile
    volumes:
     - .:/code
    environment:
     - ASPNETCORE_ENVIRONMENT=prod
  messaging:
    build:
      context: ./docker/messaging
      dockerfile: ./Dockerfile
    volumes:
     - .:/code
    environment:
     - ASPNETCORE_ENVIRONMENT=prod
  apidb:
    build:
      context: .
      dockerfile: ./docker/apidb/Dockerfile
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672"
      - "5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports:
     - "5000:80"