// <auto-generated />
namespace TaskManager.Common.Resources
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class ErrorMessages
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorMessages"/> class.
        /// </summary>
        public ErrorMessages()
        {
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the Login_AuthError key.
        /// </summary>
        public static string Login_AuthError
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Login_AuthError", ErrorMessages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ErrorMessages.resourceManager == null)
                {
                    ErrorMessages.resourceManager = new ResourceManager("TaskManager.Common.Resources.ErrorMessages", typeof(ErrorMessages).GetTypeInfo().Assembly);
                }

                return ErrorMessages.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Tasks_CompleteUnactive key.
        /// </summary>
        public static string Tasks_CompleteUnactive
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Tasks_CompleteUnactive", ErrorMessages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Tasks_InvalidStatusParameterValue key.
        /// </summary>
        public static string Tasks_InvalidStatusParameterValue
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Tasks_InvalidStatusParameterValue", ErrorMessages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Tasks_NotFound key.
        /// </summary>
        public static string Tasks_NotFound
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Tasks_NotFound", ErrorMessages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Tasks_RemoveUncompleted key.
        /// </summary>
        public static string Tasks_RemoveUncompleted
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Tasks_RemoveUncompleted", ErrorMessages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Unknown key.
        /// </summary>
        public static string Unknown
        {
            get
            {
                return ErrorMessages.ResourceManager.GetString("Unknown", ErrorMessages.CultureInfo);
            }
        }
    }
}